version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    # env_file: ./.env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
    #   - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
  nextjs-app:
    depends_on:
      - mongodb
    # build: ./
    image: nextjs-docker
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/my_db